name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with:
#           python-version: 3.x
#       - run: pip install mkdocs-material 
#       - run: mkdocs gh-deploy --force
  Sync:
#     needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages 
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 744 ~/.ssh/id_rsa
          chmod 744 ~/.ssh
      - name: Add SSH known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 744 ~/.ssh/known_hosts
      - name: Sync Repository
        run: |
          git remote add myserver ssh://${{secrets.SERVER_USERNAME}}@${{ secrets.SERVER_IP }}/personal/repo/note.git
          git push myserver gh-pages:gh-pages
      - name: Remove SSH directory
        run: rm -rf ~/.ssh
          
