name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs==1.6.0
      - run: pip install mkdocs-material==9.2.3
      - run: pip install mkdocs-material-extensions==1.1.1
      - run: pip install mkdocs-markmap
      - run: pip install mkdocs-jupyter
      - run: mkdocs gh-deploy --force
  Sync:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      REPO_PATH: /personal/repo/note
      NOTE_PATH: /personal/note
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Sync code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export ALL_PROXY=${{ secrets.SERVER_PROXY }}
            cd "${REPO_PATH}"
            find  "${NOTE_PATH}" -type f ! -name ".htaccess" ! -name ".user.ini" -delete
            find  "${NOTE_PATH}" -type d -empty -delete
            git fetch origin
            git --work-tree="${NOTE_PATH}" --git-dir="${REPO_PATH}/.git" checkout -f origin/gh-pages
