name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Connect to Server and Remove Old Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            find  /www/wwwroot/note.zerolacqua.top -type f ! -name ".htaccess" ! -name ".user.ini" -delete
            find  /www/wwwroot/note.zerolacqua.top -type d -empty -delete

      - name: Copy New Files
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.SERVER_USERNAME }} #ssh user name
          server: ${{ secrets.SERVER_IP }} #引用之前创建好的secret
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          local_path: "./" # 对应我们项目build的文件夹路径
          remote_path: "/www/wwwroot/note.zerolacqua.top"
        env:
          LANG: en_US.UTF-8
